src/Entity/Product.php
<?php

namespace App\Entity;

use App\Repository\ProductRepository;
use DateTime;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=ProductRepository::class)
 * @ORM\HasLifecycleCallbacks()
 * HasLifecycleCallbacks + méthode prePersist =>
 * Modifier l’entité pour enregister la date de création du produit à la date ou on valide le produit
 */
class Product
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=50)
     */
    private $name;

    /**
     * @ORM\Column(type="text", nullable=true)
     */
    private $description;

    /**
     * @ORM\Column(type="integer")
     */
    private $price;

    /**
     * @ORM\Column(type="date")
     */
    private $createdAt;

    /**
     * @ORM\ManyToOne(targetEntity=Category::class, inversedBy="products")
     */
    private $category;

    /**
     * Méthode exécutée avant l'insertion en base
     * @ORM\PrePersist()
     * Modifier l’entité pour enregister la date de création du produit à la date ou on valide le produit
     */
    public function prePersist()
    {
        if ($this->createdAt === null) {
            $this->createdAt = new \DateTime();
        }
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): self
    {
        $this->name = $name;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(?string $description): self
    {
        $this->description = $description;

        return $this;
    }

    public function getPrice(): ?int
    {
        return $this->price;
    }

    /**
     * Obtenir le prix en décimal: 1500 -> 15.00
     */
    public function getPriceFloat(): ?float
    {
        return $this->price === null
            ? null 
            : $this->price / 100;
    }

    public function setPrice(int $price): self
    {
        $this->price = $price;

        return $this;
    }

    public function getCreatedAt(): ?\DateTimeInterface
    {
        return $this->createdAt;
    }

    public function setCreatedAt(\DateTimeInterface $createdAt): self
    {
        $this->createdAt = $createdAt;

        return $this;
    }

    public function getCategory(): ?Category
    {
        return $this->category;
    }

    public function setCategory(?Category $category): self
    {
        $this->category = $category;

        return $this;
    }
}

src/Controller/ProductController.php
<?php

namespace App\Controller;

use App\Entity\Product;
use App\Repository\CategoryRepository;
use App\Repository\ProductRepository;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Response;

class ProductController extends AbstractController {

    /**
     * @Route("/product", name="product_list")
     */
    public function index(ProductRepository $repository, CategoryRepository $categoryRepository): Response
    {
        // Récupération de tous les produits
        $product_list = $repository->findAll();

        // Récupération de toutes les catégories
        $categories = $categoryRepository->findAll();

        return $this->render('product/index.html.twig', [
            'product_list' => $product_list,
            'categories' => $categories
        ]);
    }

    /**
     * Grace au ParamConverter (installé par frameworkExtraBundle / Annotation)
     * Symfony va récupérer l'entité Product qui correspond à l'identifiant dans l'URI
     * 
     * @Route("/product/{id}", name="product_show")
     */
    public function show(Product $product): Response
    {
        return $this->render('product/show.html.twig',[
            'product' => $product
        ]);
    }

    /** 
    * @Route("/product/{id}/category_show", name="category_show")
    */
    public function show_products_from_category($id, CategoryRepository $categoryRepository, ProductRepository $productRepository)
    {
        $products = $productRepository->findBy([
            'category' => $id
        ]);

        $categories = $categoryRepository->findAll();

        return $this->render('product/show_category.html.twig', [
            'products' => $products,
            'categories' => $categories
        ]);
    }

}

// Récupérer une entité par son ID
// $result3 = $repository->find(1); // produit ou null

// Récupérer une entité par son ID
// $result3 = $repository->findOneBy(['id'=>1]); // produit ou null 

templates/product/index.html.twig
{% extends "_template.html.twig" %}

{% block title %}Produits{% endblock %}


{% block content %}
    <div class="section">
        <h1 class="title">Liste des produits: {{ product_list|length}}</h1>

        {# Inclusion de fichiers + passage de variable #}
        {% include "includes/product_list.html.twig" with {products: product_list} %}

    </div>
{% endblock %}

{# {% block content2 %}
<div class="columns is-multiline">
    {% for product in product_list %}
        <div class="column is-one-quarter">
            <div class="card">
                <div class="card-content">
                    <p class="title">{{ product.name }}</p>
                    <p class="content">{{ product.description }}</p>
                    <h6>
                        {{product.priceFloat|number_format(2, '.', ' ') }} €
                        | {{ product.createdAt|date('d/m/Y') }}
                    </h6>
                </div>
            </div>
        </div> 
    {% endfor %}
</div>
{% endblock %} #}

templates/product/show.html.twig
{% extends "_template.html.twig" %}

{% block title %} {{product.name}} {% endblock %}

{% block content %}
<section class="section">
    <div class="columns">
        <div class="column is-two-fifth">
            <figure class="image is-1by1">
                <img src="https://loremflickr.com/1024/1024/clothes/all?lock={{ product.id }}">
            </figure>
        </div>
        
        <div class="column">
            <h1 class="title has-text-primary">
                {{product.name}}
            </h1>
            
            <p class="content">
                {{product.description}}
            </p>

            <small class="has-background-success has-text-white">{{product.category.name}}</small>
            
            <div class="tags has-addons are-large mt-4">
                <span class="tag">
                    {{product.PriceFloat|number_format(2 , '.' , ' ')}} {# . pour les centimes #}
                </span>
                <span class="tag is-primary">
                    <span class="icon"><i class="fas fa-euro-sign"></i></span>
                </span>
            </div>
            
            <hr>
            <h6 class="is-size-7">
                <span class="icon has-text-info"><i class="fas fa-info-circle"></i></span>
                <span>Produit ajouté le {{product.createdAt|date('d/m/Y')}}</span>
            </h6>
        </div>
    </div>
</section>
{% endblock %}

templates/product/show_category.html.twig
{% extends "_template.html.twig" %}

{% block title %}Liste des produits dans la catégorie: {{ products|length}}{% endblock %}

{% block content %}
    <div class="section">
        <h1 class="title">Liste des produits dans la catégorie: {{ products|length}}</h1>

        {% include "includes/product_list.html.twig" with {products:products, categories:categories} %}

    </div>
{% endblock %}